# Generated by Django 5.0.7 on 2025-10-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('block_number', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('value', models.CharField(max_length=120)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('difficulty', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('explanation', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(db_index=True, max_length=42)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rng_seed', models.BigIntegerField()),
                ('total_questions', models.IntegerField(default=10)),
                ('correct_count', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('state', models.CharField(default='ACTIVE', max_length=16)),
                ('time_limit_secs', models.IntegerField(default=10)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tx_hash', models.CharField(db_index=True, max_length=66)),
                ('block_number', models.PositiveBigIntegerField(db_index=True)),
                ('log_index', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tx_hash', 'log_index')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order_hint', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffled_options', models.JSONField()),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.quizsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.quizsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
