# Generated by Django 5.0.7 on 2025-10-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(db_index=True, max_length=42)),
                ('won', models.BooleanField()),
                ('status', models.CharField(default='PENDING', max_length=24)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chain.quizsession')),
            ],
        ),
    ]
