# Generated by Django 5.0.7 on 2025-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_settlementjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(db_index=True, max_length=42)),
                ('tournament_id', models.IntegerField()),
                ('session_id', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_address', 'played_at', 'tournament_id'], name='chain_tourn_user_ad_507e40_idx')],
            },
        ),
    ]
