# Generated by Django 5.0.7 on 2025-11-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_tournamentplaytracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='payout_amount_smallest',
            field=models.BigIntegerField(default=0),
        ),
    ]
