# Generated by Django 5.0.7 on 2025-11-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0004_quizsession_payout_amount_smallest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='recorded_on_chain',
            field=models.BooleanField(default=False, help_text='Whether this session score was recorded on blockchain'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='tournament_id',
            field=models.IntegerField(blank=True, help_text='Tournament ID if this is a tournament session', null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash for on-chain recording', max_length=66, null=True),
        ),
    ]
