# Generated by Django 5.0.7 on 2025-11-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0005_quizsession_recorded_on_chain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='recorded_on_chain',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='tournament_id',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='tx_hash',
        ),
    ]
