# Generated by Django 5.0.7 on 2025-11-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0007_quizsession_recorded_on_chain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(db_index=True, unique=True)),
                ('custom_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tournament Metadata',
                'verbose_name_plural': 'Tournament Metadata',
                'db_table': 'tournament_metadata',
            },
        ),
    ]
